auto: true

markdown: kramdown
input: GFM
highlighter: rouge

gems: [jekyll-paginate]
permalink: none
paginate: 5
paginate_path: "/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Comments
disqus_shortname:   tianjie

title:
url: https://violettianjie.github.io
feed: /atom.xml
author_info: <a href="/">tianjie</a>
