auto: true

markdown: kramdown
input: GFM
highlighter: rouge

gems: [jekyll-paginate]
permalink: none
paginate: 5
paginate_path: "/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Comments
disqus_shortname:   linfeng365

title: linfeng365
url: https://linfeng365.github.io
feed: /atom.xml
author_info: <a href="/">linfeng365</a>
